### ISSUE TITLE
Añadir doctest; a la función es_par

### ISSUE THREAD

**Issue by zerasul** [zerasul/hacktobertest#3]
Añadir los comentarios pertinentes a la función ```es_par``` para que tenga soporte para doctest.

* Antes de hacer esta issue debe estar completada #2.

Para más información acerca de doctest, mirar este [enlace](https://docs.python.org/es/3/library/doctest.html).

**Comment by ana-med** [comment]
@zerasul Me he dado cuenta de que hice esto al hacer la issue #2

**Comment by zerasul** [comment]
Cierto; pues otra issue hecha. Voy a enlazarlo con el pull request de antes.
