### ISSUE TITLE
Corregir la función Div para en caso de dividir por 0 devuelva un error

### ISSUE THREAD

**Issue by zerasul** [zerasul/hacktobertest#4]
La función ```div```, permite dividir por 0. Hay que añadir una comprobación para que devuelva un error; en este caso será una excepción.

* No olvides de añadir el comentario con el doctest.

**Comment by GSantos23** [comment]
Me gustaria trabajar en este problema. Sigue abierto?

**Comment by zerasul** [comment]
Ya la tienes asignada.
